outFolder: results/
variants: inputs/BigBrain_trans-eQTL_top_assoc_peer10.variant.list.bed                                      # Expects headerless file with columns - chr, start, end, variant_id
full_assoc_sumstat: /sc/arion/projects/bigbrain/kailash/trans/ALL_eQTL/peer10/BigBrain_trans-eQTL_PEER10_full_assoc.sorted.tsv.gz     # Expects gzipped file with first line as column name
n_splits: 1000
threads: 4

# Software setting
R_version: "R/4.2.0"
TABIX_version: "tabix/0.2.6"

chunk_prefix: variants.part

split_variants_script: scripts/split_variants.R
read_bigbrain_script: scripts/read_bigbrain.R
join_bigbrain_script: scripts/join_bigbrain.R

join_group_size: 8
join_cores: 10
